### ISSUE TITLE
I can't login.

### ISSUE THREAD

**Issue by AquaDef** [AngryCarrot789/PSWRDMGR#1]
Hi, I'm unable to find the login password as I'm a beginner in WPF. Help is appreciated

**Comment by AngryCarrot789** [comment]
its the same as your username, aka the folder in C:\Users

**Comment by AngryCarrot789** [comment]
if not you cna change it in App.xaml.cs at line 59 where it says Environment.Username

**Comment by AquaDef** [comment]
Thank you for support.
It worked!
